// Code generated by hertz generator.

package main

import (
	"diploma_search/biz/client"
	"diploma_search/biz/config"

	"html/template"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/network/standard"
)

func subtractionOne(num int) int {
	return num - 1
}

func main() {
	// 延迟关闭GRPC连接
	defer client.Conn.Close()
	h := server.Default(
		//读取配置文件端口
		server.WithHostPorts("localhost:"+config.C.Server.Port),
		server.WithMaxRequestBodySize(20<<20),
		server.WithTransport(standard.NewTransporter),
	)
	//自定义解析
	h.Delims("{[{", "}]}")
	h.SetFuncMap(template.FuncMap{
		"subtractionOne": subtractionOne,
	})

	h.LoadHTMLGlob("ui/template/views/**")
	//静态文件加载
	h.Static("static", "ui/template")
	register(h)
	h.Spin()

}
