// Code generated by hertz generator.

package main

import (
	"diploma_search/biz/handler"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/", handler.ViewIndex)
	r.GET("/index", handler.ViewIndex)
	r.GET("/search", handler.ViewSearch)
}
