apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcserver
  namespace: diploma-search
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpcserver
  template:
    metadata:
      labels:
        app: grpcserver
    spec:
      containers:
        - name: grpcserver
          image: grpc_server:v1.1
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 9110
          args: ["-meili_url", "meilisearch:7700"]
---
apiVersion: v1
kind: Service
metadata:
  name: grpcserver
  namespace: diploma-search
spec:
  type: NodePort
  selector:
    app: grpcserver
  ports:
    - port: 9110
      targetPort: 9110
