apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
  namespace: diploma-search
spec:
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.1
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 7700
---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch
  namespace: diploma-search
spec:
  type: NodePort
  selector:
    app: meilisearch
  ports:
    - port: 7700
      targetPort: 7700
