apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  namespace: diploma-search
spec:
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: search
          image: search_app:v1.1
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
          args: ["-grpc_url", "grpcserver:9110"]
---
apiVersion: v1
kind: Service
metadata:
  name: search
  namespace: diploma-search
spec:
  type: NodePort
  selector:
    app: search
  ports:
    - port: 5000
      targetPort: 5000
